export default [
	{
		tags: {
			Event: "?",
			Site: "?",
			Date: {
				value: "????.??.??",
				year: "????",
				month: "??",
				day: "??",
			},
			Round: "?",
			White: "?",
			Black: "?",
			Result: "*",
			messages: [],
		},
		gameComment: null,
		moves: [
			{
				moveNumber: 1,
				notation: {
					fig: null,
					strike: null,
					col: "e",
					row: "4",
					check: null,
					promotion: null,
					notation: "e4",
				},
				variations: [
					[
						{
							moveNumber: 1,
							notation: {
								fig: null,
								strike: null,
								col: "e",
								row: "3",
								check: null,
								promotion: null,
								notation: "e3",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "w",
						},
						{
							moveNumber: null,
							notation: {
								fig: null,
								strike: null,
								col: "c",
								row: "6",
								check: null,
								promotion: null,
								notation: "c6",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "b",
						},
					],
				],
				nag: null,
				commentDiag: null,
				turn: "w",
			},
			{
				moveNumber: 1,
				notation: {
					fig: null,
					strike: null,
					col: "d",
					row: "5",
					check: null,
					promotion: null,
					notation: "d5",
				},
				variations: [
					[
						{
							moveNumber: 1,
							notation: {
								fig: null,
								strike: null,
								col: "b",
								row: "6",
								check: null,
								promotion: null,
								notation: "b6",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "b",
						},
						{
							moveNumber: 2,
							notation: {
								fig: null,
								strike: null,
								col: "d",
								row: "4",
								check: null,
								promotion: null,
								notation: "d4",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "w",
						},
						{
							moveNumber: null,
							notation: {
								fig: null,
								strike: null,
								col: "h",
								row: "6",
								check: null,
								promotion: null,
								notation: "h6",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "b",
						},
						{
							moveNumber: 3,
							notation: {
								fig: null,
								strike: null,
								col: "c",
								row: "4",
								check: null,
								promotion: null,
								notation: "c4",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "w",
						},
					],
					[
						{
							moveNumber: 1,
							notation: {
								fig: null,
								strike: null,
								col: "b",
								row: "5",
								check: null,
								promotion: null,
								notation: "b5",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "b",
						},
						{
							moveNumber: 2,
							notation: {
								fig: null,
								strike: null,
								col: "d",
								row: "4",
								check: null,
								promotion: null,
								notation: "d4",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "w",
						},
						{
							moveNumber: null,
							notation: {
								fig: null,
								strike: null,
								col: "c",
								row: "5",
								check: null,
								promotion: null,
								notation: "c5",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "b",
						},
						{
							moveNumber: 3,
							notation: {
								fig: null,
								strike: null,
								col: "f",
								row: "4",
								check: null,
								promotion: null,
								notation: "f4",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "w",
						},
						{
							moveNumber: null,
							notation: {
								fig: null,
								strike: null,
								col: "f",
								row: "6",
								check: null,
								promotion: null,
								notation: "f6",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "b",
						},
						{
							moveNumber: 4,
							notation: {
								fig: null,
								strike: null,
								col: "g",
								row: "3",
								check: null,
								promotion: null,
								notation: "g3",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "w",
						},
						{
							moveNumber: null,
							notation: {
								fig: null,
								strike: null,
								col: "g",
								row: "6",
								check: null,
								promotion: null,
								notation: "g6",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "b",
						},
						{
							moveNumber: 5,
							notation: {
								fig: null,
								strike: null,
								col: "h",
								row: "3",
								check: null,
								promotion: null,
								notation: "h3",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "w",
						},
						{
							moveNumber: null,
							notation: {
								fig: "B",
								strike: null,
								col: "g",
								row: "7",
								check: null,
								promotion: null,
								notation: "Bg7",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "b",
						},
						{
							moveNumber: 6,
							notation: {
								fig: null,
								strike: null,
								col: "d",
								row: "5",
								check: null,
								promotion: null,
								notation: "d5",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "w",
						},
						{
							moveNumber: null,
							notation: {
								fig: null,
								strike: null,
								col: "g",
								row: "5",
								check: null,
								promotion: null,
								notation: "g5",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "b",
						},
						{
							moveNumber: 7,
							notation: {
								fig: null,
								disc: "f",
								strike: "x",
								col: "g",
								row: "5",
								check: null,
								promotion: null,
								notation: "fxg5",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "w",
						},
						{
							moveNumber: null,
							notation: {
								fig: null,
								strike: null,
								col: "b",
								row: "4",
								check: null,
								promotion: null,
								notation: "b4",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "b",
						},
						{
							moveNumber: 8,
							notation: {
								fig: null,
								disc: "g",
								strike: "x",
								col: "f",
								row: "6",
								check: null,
								promotion: null,
								notation: "gxf6",
							},
							variations: [],
							nag: null,
							commentDiag: null,
							turn: "w",
						},
					],
				],
				nag: null,
				commentDiag: null,
				turn: "b",
			},
		],
		messages: [],
	},
]

/* 
Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "*"]

1. e4 ( 1. e3 c6 ) 1... d5 ( 1... b6 2. d4 h6 3. c4 ) ( 1... b5 2. d4 c5 3. f4 f6 4. g3 g6 5. h3 Bg7 6. d5 g5 7. fxg5 b4 8. gxf6 ) *



*/
